language: cpp
matrix:
  include:
    - os: linux
      compiler: g++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'bc']
      env:
        COMPILER=g++-5
        FLAGS="-std=c++14 -O2 -Wall -Wextra -Wno-unused-result -Werror"
        GCOV=gcov-5

    - os: linux
      compiler: g++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'bc']
      env:
        COMPILER=g++-6
        FLAGS="-std=c++14 -O2 -Wall -Wextra -Wno-unused-result -Werror"
        GCOV=gcov-6

    - os: linux
      compiler: clang++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8', 'llvm-toolchain-precise']
          packages: ['clang-3.8', 'bc']
      env:
        COMPILER=clang-3.8
        FLAGS="-std=c++14 -O2 -Wall -Wextra -Wno-unused-result -Werror -lstdc++"

sudo: false

script:
  - cp -r docs docs-spec
  - rm -rf docs/cpp
  - ./gendoc.sh
  - diff -r docs docs-spec
  - ulimit -s unlimited
  - ulimit -a
  - $COMPILER --version
  - CXX=$COMPILER CXXFLAGS=$FLAGS ./cpp/spec.sh --all
notifications:
  email: false
